name = "backend"
compatibility_date = "2024-07-21"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWU2NTg3NzAtY2ZlYy00ODNiLWE5M2YtZjY2MWM2MGIzZmNiIiwidGVuYW50X2lkIjoiOGFmYTkxMzY5YWQ2YzcwZTA3NzdiNTRkYmNlNWUyYzAzNGRkMzc1Yjg0MWZlMTZkMjE3ZGU4YTZjOGNmMDkyOCIsImludGVybmFsX3NlY3JldCI6ImQ4ZDFhODQ3LWE0ZjItNGQxNi1hYmMzLTJiNjRjOTYxZDBhZSJ9.0ZzPxd7IMRsJTWmFlI8ySEHjlPuXRItrBBGXNmrX3VM"
JWT_SECRET = "myjwtsecret"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"